AppWeb/Models/ErrorViewModel.cs
namespace AppWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppWeb/Models/Humans.cs
namespace AppWeb.Models
{
    public class Humans
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Year {  get; set; }
    }
}

AppWeb/Controllers/HomeController.cs
using System.Diagnostics;
using AppWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace AppWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppWeb/Controllers/HumanController.cs
using System;
using AppWeb.DataBase;
using AppWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace AppWeb.Controllers
{
	public class HumanController : Controller
	{
		private readonly DB _context;
		public HumanController(DB DataBase)
		{
			_context = DataBase;

		}
		[HttpGet]
		public ActionResult Read()
		{
			if(_context.human.IsNullOrEmpty())
			{
				var list=new List<Humans>();
				return View(list);
			}
			else
			{
				return View(_context.human.ToList());

			}

		}
		[HttpPost]
		public ActionResult Delete(int Id,int Year,string Name)
		{
			var human = _context.human.Find(Id);
			_context.human.Remove(human);
			_context.SaveChanges();
			return RedirectToAction("Read");

		}
		public ActionResult Create(int Id,string Name,int Year)
		{
			Humans humans = new Humans();
			humans.Name = Name;
			humans.Year = Year;
			_context.Add(humans);
			_context.SaveChanges();
			return RedirectToAction("Read");

		}
		[HttpPost]
		public ActionResult Edit(string Name, int Id,int Year)
		{
			var humans = _context.human.Find(Id);
			humans.Name=Name;
			humans.Id = Id;
			humans.Year=Year;
			_context.human.Update(humans);
			_context.SaveChanges();
			return RedirectToAction("Read");


		}

	}
}

AppWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppWeb/Views/Human/Read.cshtml
<div>
	@foreach (var i in Model)
	{
		<p>@i.Name----@i.Year</p>
		<form method="post" action="Delete">
			<button type="submit" name="Id" value="@i.Id">Delete</button>

		</form>
	}
</div>
	

<div>
	<h2>Create Human</h2>
	<form method="post" action="Create">
		<p>
			<input type="text" name="Name" placeholder="Create Human name">
			<input type="number" name="Year" placeholder="Create Human year">
			<button type="submit">Create</button>
		</p>
	</form>

</div>
<div>
	<h2>Edit Human</h2>
	<form method="post" action="Edit">
		<p>
			<input type="text" name="Name" placeholder="Edit Human name">
			<input type="number" name="Year" placeholder="Edit Human year">
			<button type="submit">Edit</button>
		</p>
	</form>
</div>

AppWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Human" asp-action="Read">Humans</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AppWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>